# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Insider
tagline:             'Life'
description:         'Site about Life'
url:                 https://germany.bestwow.net
baseurl:             'https://germany.bestwow.net'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
